// Code generated by internal/tools/permissiongen. DO NOT EDIT.
//
// 唯一信源：api/permissions/catalog.yaml
// 重新生成：make gen

package rbac

// 权限码常量。代码中一律引用这些常量，不得出现权限码字符串字面量。
const (
	// PermissionRbacRoleRead 读取角色定义与角色列表
	PermissionRbacRoleRead PermissionCode = "rbac.role.read"

	// PermissionRbacRoleWrite 创建、修改、删除角色。属不可逆操作
	PermissionRbacRoleWrite PermissionCode = "rbac.role.write"

	// PermissionRbacSubjectRead 读取主体的角色绑定关系
	PermissionRbacSubjectRead PermissionCode = "rbac.subject.read"

	// PermissionRbacSubjectAssign 为主体授予或回收角色，会改变权限边界
	PermissionRbacSubjectAssign PermissionCode = "rbac.subject.assign"

	// PermissionRbacScopeRead 读取范围目录：这个部署里登记了哪些范围
	PermissionRbacScopeRead PermissionCode = "rbac.scope.read"

	// PermissionRbacScopeWrite 登记范围、改显示名、删除范围。删除属不可逆操作
	PermissionRbacScopeWrite PermissionCode = "rbac.scope.write"

	// PermissionRbacPolicyPublish 使一次角色变更正式生效（缓存失效与生效确认）
	PermissionRbacPolicyPublish PermissionCode = "rbac.policy.publish"

	// PermissionAuditLogRead 查阅审计日志
	PermissionAuditLogRead PermissionCode = "audit.log.read"

	// PermissionAuditLogExport 导出审计日志。属批量操作
	PermissionAuditLogExport PermissionCode = "audit.log.export"

	// PermissionTelemetryRead 读取客户端遥测的计数与明细（Web/CLI 本地动作）。只读
	PermissionTelemetryRead PermissionCode = "telemetry.read"

	// PermissionGalaxyProjectRead 读取自己创建的工程、草稿与版本
	PermissionGalaxyProjectRead PermissionCode = "galaxy.project.read"

	// PermissionGalaxyProjectWrite 创建、修改、删除工程，保存版本。删除属不可逆操作
	PermissionGalaxyProjectWrite PermissionCode = "galaxy.project.write"

	// PermissionGalaxyProjectPublish 发布与撤回发布。唯一一个让内容离开私有边界的动作
	PermissionGalaxyProjectPublish PermissionCode = "galaxy.project.publish"

	// PermissionGalaxyAssetRead 读取自己工程下的资产列表与读取地址
	PermissionGalaxyAssetRead PermissionCode = "galaxy.asset.read"

	// PermissionGalaxyAssetWrite 上传与删除工程资产
	PermissionGalaxyAssetWrite PermissionCode = "galaxy.asset.write"

	// PermissionAll 全部权限。仅保留给系统管理员角色，不得授予其他角色
	PermissionAll PermissionCode = "*"
)

// AllPermissionCodes 是权限目录的全集，顺序与 catalog.yaml 一致。
var AllPermissionCodes = []PermissionCode{
	PermissionRbacRoleRead,
	PermissionRbacRoleWrite,
	PermissionRbacSubjectRead,
	PermissionRbacSubjectAssign,
	PermissionRbacScopeRead,
	PermissionRbacScopeWrite,
	PermissionRbacPolicyPublish,
	PermissionAuditLogRead,
	PermissionAuditLogExport,
	PermissionTelemetryRead,
	PermissionGalaxyProjectRead,
	PermissionGalaxyProjectWrite,
	PermissionGalaxyProjectPublish,
	PermissionGalaxyAssetRead,
	PermissionGalaxyAssetWrite,
	PermissionAll,
}

// 内置角色标识。一经发布不可更改。
const (
	// RoleSystemAdmin 系统管理员
	RoleSystemAdmin = "system.admin"

	// RoleRbacAdmin 权限管理员
	RoleRbacAdmin = "rbac.admin"

	// RoleAuditor 审计员
	RoleAuditor = "auditor"

	// RoleViewer 只读用户
	RoleViewer = "viewer"

	// RoleGalaxyAuthor 创作者
	RoleGalaxyAuthor = "galaxy.author"
)

// BuiltinRoles 是内置角色定义，由权限目录派生。
var BuiltinRoles = []RoleDefinition{
	{
		ID:          RoleSystemAdmin,
		DisplayName: "系统管理员",
		Builtin:     true,
		Permissions: []PermissionCode{
			PermissionAll,
		},
		Inherits:              nil,
		MutuallyExclusiveWith: nil,
	},
	{
		ID:          RoleRbacAdmin,
		DisplayName: "权限管理员",
		Builtin:     true,
		Permissions: []PermissionCode{
			PermissionRbacRoleRead,
			PermissionRbacRoleWrite,
			PermissionRbacSubjectRead,
			PermissionRbacSubjectAssign,
			PermissionRbacScopeRead,
			PermissionRbacScopeWrite,
			PermissionRbacPolicyPublish,
		},
		Inherits:              nil,
		MutuallyExclusiveWith: nil,
	},
	{
		ID:          RoleAuditor,
		DisplayName: "审计员",
		Builtin:     true,
		Permissions: []PermissionCode{
			PermissionAuditLogRead,
			PermissionAuditLogExport,
			PermissionTelemetryRead,
			PermissionRbacRoleRead,
			PermissionRbacSubjectRead,
			PermissionRbacScopeRead,
		},
		Inherits:              nil,
		MutuallyExclusiveWith: nil,
	},
	{
		ID:          RoleViewer,
		DisplayName: "只读用户",
		Builtin:     true,
		Permissions: []PermissionCode{
			PermissionRbacRoleRead,
			PermissionRbacSubjectRead,
			PermissionRbacScopeRead,
		},
		Inherits:              nil,
		MutuallyExclusiveWith: nil,
	},
	{
		ID:          RoleGalaxyAuthor,
		DisplayName: "创作者",
		Builtin:     true,
		Permissions: []PermissionCode{
			PermissionGalaxyProjectRead,
			PermissionGalaxyProjectWrite,
			PermissionGalaxyProjectPublish,
			PermissionGalaxyAssetRead,
			PermissionGalaxyAssetWrite,
		},
		Inherits:              nil,
		MutuallyExclusiveWith: nil,
	},
}
