// Command permissiongen 从权限目录生成 Go 与 TypeScript 常量。
//
// 用法（在仓库根目录执行）：
//
//	go run ./internal/tools/permissiongen
//
// 输入：api/permissions/catalog.yaml（权限码全集的唯一信源）
// 输出：internal/rbac/catalog_gen.go
// 输出：web/src/gen/permission-codes.ts
//
// 本工具是"同一件事唯一入口"的体现：两端常量不可能各自漂移，
// 因为它们来自同一次生成。生成产物由 catalog_test.go 校验是否同步。
package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"unicode"

	"gopkg.in/yaml.v3"
)

type catalog struct {
	Version     int          `yaml:"version"`
	Permissions []permission `yaml:"permissions"`
	Roles       []role       `yaml:"roles"`
}

type permission struct {
	Code        string `yaml:"code"`
	Description string `yaml:"description"`
}

type role struct {
	ID                    string   `yaml:"id"`
	DisplayName           string   `yaml:"display_name"`
	Builtin               bool     `yaml:"builtin"`
	Permissions           []string `yaml:"permissions"`
	Inherits              []string `yaml:"inherits"`
	MutuallyExclusiveWith []string `yaml:"mutually_exclusive_with"`
}

// codePattern 限定权限码形状：至少两段，全小写、点分、下划线分词；
// 通配只允许出现在末段，或独占整个权限码。
var codePattern = regexp.MustCompile(`^(\*|[a-z][a-z0-9_]*(\.[a-z][a-z0-9_]*)*(\.[a-z*][a-z0-9_]*)?)$`)

func main() {
	root := flag.String("root", ".", "仓库根目录")
	check := flag.Bool("check", false, "只校验生成产物是否与目录同步，不写文件")
	flag.Parse()

	if err := run(*root, *check); err != nil {
		fmt.Fprintf(os.Stderr, "permissiongen: %v\n", err)
		os.Exit(1)
	}
}

func run(root string, check bool) error {
	// 路径由 -root 命令行参数与固定文件名拼成，是本工具的输入契约。
	raw, err := os.ReadFile(filepath.Join(root, "api/permissions/catalog.yaml")) //nolint:gosec // 路径来自本工具自身的参数
	if err != nil {
		return err
	}
	var c catalog
	dec := yaml.NewDecoder(bytes.NewReader(raw))
	dec.KnownFields(true)
	if err := dec.Decode(&c); err != nil {
		return fmt.Errorf("解析 catalog.yaml: %w", err)
	}
	if err := validate(c); err != nil {
		return err
	}

	goSource, err := format.Source([]byte(renderGo(c)))
	if err != nil {
		return fmt.Errorf("生成的 Go 源码无法格式化: %w", err)
	}

	outputs := map[string]string{
		filepath.Join(root, "internal/rbac/catalog_gen.go"):    string(goSource),
		filepath.Join(root, "web/src/gen/permission-codes.ts"): renderTS(c),
	}
	for path, content := range outputs {
		if check {
			// path 是下方 outputs 的固定键，非外部输入。
			existing, err := os.ReadFile(path) //nolint:gosec // 路径来自本工具自身的常量
			if err != nil || string(existing) != content {
				return fmt.Errorf("%s 与 api/permissions/catalog.yaml 不同步，请运行 make gen", path)
			}
			continue
		}
		// 0644 是源码文件的常规权限；生成产物不是机密，gosec 在此为误报。
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil { //nolint:gosec // 生成的是源码，按常规权限落盘
			return err
		}
		fmt.Printf("生成 %s\n", path)
	}
	return nil
}

func validate(c catalog) error {
	if c.Version != 1 {
		return fmt.Errorf("不支持的 catalog 版本 %d", c.Version)
	}
	if len(c.Permissions) == 0 {
		return fmt.Errorf("权限目录为空")
	}

	seenCode := map[string]bool{}
	seenIdent := map[string]string{}
	for _, p := range c.Permissions {
		if !codePattern.MatchString(p.Code) {
			return fmt.Errorf("权限码 %q 不合法：应形如 domain.resource.action", p.Code)
		}
		if p.Description == "" {
			return fmt.Errorf("权限码 %q 缺少 description", p.Code)
		}
		if seenCode[p.Code] {
			return fmt.Errorf("权限码 %q 重复", p.Code)
		}
		seenCode[p.Code] = true
		ident := "Permission" + identifier(p.Code)
		if prev, ok := seenIdent[ident]; ok {
			return fmt.Errorf("权限码 %q 与 %q 生成的标识符同名（%s），请调整命名", p.Code, prev, ident)
		}
		seenIdent[ident] = p.Code
	}

	seenRole := map[string]bool{}
	for _, r := range c.Roles {
		if r.ID == "" {
			return fmt.Errorf("角色缺少 id")
		}
		if seenRole[r.ID] {
			return fmt.Errorf("角色 %q 重复", r.ID)
		}
		seenRole[r.ID] = true
		for _, pid := range r.Permissions {
			if !seenCode[pid] {
				return fmt.Errorf("角色 %q 引用了未登记的权限码 %q", r.ID, pid)
			}
		}
	}
	return nil
}

// identifier 把权限码或角色标识转换为 Go 标识符主体，例如
// "rbac.role.read" -> "RbacRoleRead"，"*" -> "All"。
func identifier(code string) string {
	if code == "*" {
		return "All"
	}
	var b strings.Builder
	for _, seg := range strings.Split(code, ".") {
		if seg == "*" {
			b.WriteString("All")
			continue
		}
		for _, word := range strings.Split(seg, "_") {
			if word == "" {
				continue
			}
			runes := []rune(word)
			runes[0] = unicode.ToUpper(runes[0])
			b.WriteString(string(runes))
		}
	}
	return b.String()
}

func renderGo(c catalog) string {
	var b strings.Builder
	b.WriteString("// Code generated by internal/tools/permissiongen. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// 唯一信源：api/permissions/catalog.yaml\n")
	b.WriteString("// 重新生成：make gen\n\n")
	b.WriteString("package rbac\n\n")

	b.WriteString("// 权限码常量。代码中一律引用这些常量，不得出现权限码字符串字面量。\nconst (\n")
	for _, p := range c.Permissions {
		fmt.Fprintf(&b, "\t// %s %s\n", "Permission"+identifier(p.Code), p.Description)
		fmt.Fprintf(&b, "\t%s PermissionCode = %q\n\n", "Permission"+identifier(p.Code), p.Code)
	}
	b.WriteString(")\n\n")

	b.WriteString("// AllPermissionCodes 是权限目录的全集，顺序与 catalog.yaml 一致。\n")
	b.WriteString("var AllPermissionCodes = []PermissionCode{\n")
	for _, p := range c.Permissions {
		fmt.Fprintf(&b, "\t%s,\n", "Permission"+identifier(p.Code))
	}
	b.WriteString("}\n\n")

	b.WriteString("// 内置角色标识。一经发布不可更改。\nconst (\n")
	for _, r := range c.Roles {
		fmt.Fprintf(&b, "\t// Role%s %s\n", identifier(r.ID), r.DisplayName)
		fmt.Fprintf(&b, "\tRole%s = %q\n\n", identifier(r.ID), r.ID)
	}
	b.WriteString(")\n\n")

	b.WriteString("// BuiltinRoles 是内置角色定义，由权限目录派生。\n")
	b.WriteString("var BuiltinRoles = []RoleDefinition{\n")
	for _, r := range c.Roles {
		b.WriteString("\t{\n")
		fmt.Fprintf(&b, "\t\tID:          Role%s,\n", identifier(r.ID))
		fmt.Fprintf(&b, "\t\tDisplayName: %q,\n", r.DisplayName)
		fmt.Fprintf(&b, "\t\tBuiltin:     %t,\n", r.Builtin)
		b.WriteString("\t\tPermissions: []PermissionCode{\n")
		for _, p := range r.Permissions {
			fmt.Fprintf(&b, "\t\t\t%s,\n", "Permission"+identifier(p))
		}
		b.WriteString("\t\t},\n")
		writeStringSlice(&b, "Inherits", r.Inherits)
		writeStringSlice(&b, "MutuallyExclusiveWith", r.MutuallyExclusiveWith)
		b.WriteString("\t},\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func writeStringSlice(b *strings.Builder, field string, values []string) {
	if len(values) == 0 {
		fmt.Fprintf(b, "\t\t%s: nil,\n", field)
		return
	}
	fmt.Fprintf(b, "\t\t%s: []string{\n", field)
	for _, v := range values {
		fmt.Fprintf(b, "\t\t\t%q,\n", v)
	}
	b.WriteString("\t\t},\n")
}

func renderTS(c catalog) string {
	var b strings.Builder
	b.WriteString("// Code generated by internal/tools/permissiongen. DO NOT EDIT.\n")
	b.WriteString("//\n")
	b.WriteString("// 唯一信源：api/permissions/catalog.yaml\n")
	b.WriteString("// 重新生成：make gen\n")
	b.WriteString("//\n")
	b.WriteString("// 前端一律引用这些常量；源码中不得出现权限码字符串字面量。\n\n")

	b.WriteString("export const PermissionCodes = {\n")
	for _, p := range c.Permissions {
		fmt.Fprintf(&b, "  /** %s */\n", sanitizeComment(p.Description))
		fmt.Fprintf(&b, "  %s: '%s',\n", identifier(p.Code), p.Code)
	}
	b.WriteString("} as const\n\n")

	b.WriteString("export type PermissionCode = (typeof PermissionCodes)[keyof typeof PermissionCodes]\n\n")

	b.WriteString("export const BuiltinRoleIds = {\n")
	for _, r := range c.Roles {
		fmt.Fprintf(&b, "  /** %s */\n", sanitizeComment(r.DisplayName))
		fmt.Fprintf(&b, "  %s: '%s',\n", identifier(r.ID), r.ID)
	}
	b.WriteString("} as const\n\n")

	b.WriteString("export type BuiltinRoleId = (typeof BuiltinRoleIds)[keyof typeof BuiltinRoleIds]\n")
	return b.String()
}

// sanitizeComment 防止目录中的文本提前闭合 TS 块注释。
func sanitizeComment(s string) string {
	return strings.ReplaceAll(s, "*/", "*\\/")
}
